# meta_compiler.py

import os
import hashlib
from datetime import datetime

BUILD_DIR = "generated_modules"


class MetaCompiler:

    def __init__(self):
        os.makedirs(BUILD_DIR, exist_ok=True)

    # -------------------------
    # Compile Mutation
    # -------------------------
    def compile(self, mutation):

        code = self.generate_code(mutation)

        filename = self._build_name(code)

        path = f"{BUILD_DIR}/{filename}.py"

        with open(path, "w") as f:
            f.write(code)

        return path

    # -------------------------
    def generate_code(self, mutation):

        return f"""
# Auto-generated by MetaCompiler
# mutation: {mutation['id']}

class GeneratedWorker:

    def execute(self, payload):
        print("Running mutation:", "{mutation['type']}")
        return payload
"""

    # -------------------------
    def _build_name(self, code):
        h = hashlib.sha256(code.encode()).hexdigest()[:12]
        return f"module_{h}"